### ISSUE TITLE
About dcnv2 

### ISSUE THREAD

**Issue by blue-531** [redrock303/NeRFLiX_CPVR2023#10]
As mentioned in #9 , I also have difficulty recompiling dcnv2. Could you please provide me with a more detailed description of installing dcnv2?

**Comment by redrock303** [comment]
Sorry to hear that, you can adopt another dcnv2 implementations that can be successfully compiled on your machine. There are some dcnv2 projects: https://github.com/CharlesShang/DCNv2, https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch, https://github.com/redrock303/Revisiting-Temporal-Alignment-for-Video-Restoration.
