### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by christina284** [redrock303/NeRFLiX_CPVR2023#13]
Hello and thank you for your work. I was wondering about the datasets we are told to download for the training. Are there links for these datasets in order to have the exact data that the code was meant for?  Also, is there a missing file named train/dataset/vimeo.py or should we create it ?

**Comment by redrock303** [comment]
Apologies for the confusion. The data loader for videos can be found at /train/dataset/vimeo_7f.py.
