### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rishavbb** [redrock303/NeRFLiX_CPVR2023#3]
Hi,

Firstly, thanks for the great piece of work. I am facing this issue:

`ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`

I have tried uninstalling and then reinstalling Pytorch as well.

**Comment by redrock303** [comment]
I have not faced this issue when building it on my local machine. And I have just asked the chatpgt, it suggests that you may install incorrect versions of pytorch/cuda.  Please also see the question here https://github.com/redrock303/NeRFLiX_CPVR2023/issues/2. 
 There are the potential solutions raised by chatgpt:
The error message "ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory" indicates that your Python code is attempting to import a library called "libtorch_cuda_cu.so", but it cannot find the library file in the expected directory.

This error usually occurs when you are using PyTorch with CUDA support, and the required library file is missing or not installed correctly. To fix this error, you may need to take one or more of the following steps:

1. Check that you have installed the correct version of PyTorch that matches your CUDA version. You can check the CUDA version using the command `nvcc --version`, and you can download the appropriate version of PyTorch from the official PyTorch website.

2. Ensure that CUDA is properly installed on your system. You may need to install the CUDA toolkit and add the CUDA bin and library directories to your system PATH.

3. Check that the required library file "libtorch_cuda_cu.so" is present in the correct directory. You may need to reinstall PyTorch or CUDA to ensure that the library file is installed correctly.

4. Check that the environment variables related to CUDA and PyTorch are set correctly. You can check the variables `LD_LIBRARY_PATH` and `TORCH_CUDA_ARCH_LIST` to ensure that they are set to the correct values.

5. If none of the above steps work, you may need to reinstall PyTorch and/or CUDA, or contact the PyTorch community for further assistance.
Also, you can use another DCN lib that works for your environment.
