### ISSUE TITLE
About Inconsistencies

### ISSUE THREAD

**Issue by hdzmtsssw** [redrock303/NeRFLiX_CPVR2023#4]
Hi, thank you for your excellent work!
I successfully used the model you provided to infer my own data and the results are fantastic. However, when I render a video path, I noticed some inconsistencies, particularly with regards to lighting, which were not present in the original NeRF results. This has resulted in severe flickering throughout the entire video. Do you have any insights on this issue? Is it necessary to train the model individually for each scene to achieve better performance?

**Comment by redrock303** [comment]
It's good to hear that NeRFLiX improves the quality of your results. The sharp illumination changes observed across the Nerf results and their reference views could possibly be attributed to this issue. In such cases, finetuning may not be effective, as most of the high-quality content and lighting conditions of reference views will be propagated and aggregated to restore enhanced results. Nevertheless, finetuning could potentially enhance the details of your results. To achieve consistent (i.e., lighting) novel view results, it is recommended to carefully design your render path. Last, I think exploring implicit multi-view consistency constrain is also an interesting topic to delve into, which may also help to alleviate this issue.
