### ISSUE TITLE
Environment problem

### ISSUE THREAD

**Issue by oakshy** [redrock303/NeRFLiX_CPVR2023#9]
Hi, thanks for your impressive work!

When I run test_novelviews.py with the pretrained model I meet this error
![ee293484-bb44-4e4a-9d08-c8d322cb57cf](https://github.com/redrock303/NeRFLiX_CVPR2023/assets/33533552/f4380e54-cfa8-4684-a2e9-ef1242cb491e)
I guess it may be related to some environment and compilation issues, do you have any suggestions for this error?

**Comment by redrock303** [comment]
you need to recompile the DCN lib in your own machine

**Comment by oakshy** [comment]
Thanks, problem solved!

**Comment by Szy-Young** [comment]
> Thanks, problem solved!

Hi @AY1997 , can you plz share with me how to recompile this DCN lib?
